export const NIGERIAN_STATES: string[] = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT (Abuja)",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers (Port Harcourt)",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const POPULAR_NIGERIAN_STATES = ["Lagos", "FCT (Abuja)", "Rivers (Port Harcourt)"];

export const POPULAR_NIGERIAN_STATE_SET = new Set<string>(POPULAR_NIGERIAN_STATES);
